/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Renafox (https://sketchfab.com/kryik1023)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lab-things-6ed351eea02e4aefb6c3aad80a763890
Title: Lab Things
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three'
import { useLoader } from '@react-three/fiber'


const Lab = (props) => {

  const { nodes, materials } = useGLTF('/models/lab_things.glb');
  
  // Load a texture (an image to display on the laptop screen)
  const screenTexture = useLoader(TextureLoader, '/textures/laptop/Material_2_baseColor.png')
  

  return (
    <group {...props} dispose={null}>
      <group position={[46.433, 15.042, -17.359]} rotation={[0, -0.94, 0]}>

        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box002_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[6.866, 40.44, 95.134]}
        ></mesh>
      </group>
      <group position={[0, 37.912, 10.411]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object001_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[-0.385, 17.57, 0]}>

            

        </mesh>
      </group>
      <group position={[-54.782, 9.163, -39.821]} rotation={[Math.PI, -1.084, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object002_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[6.153, 46.318, 50.053]}
        >
          
        </mesh>
      </group>
      <group position={[-24.338, 8.682, -29.542]} rotation={[0, -1.121, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Object003_Material_#2_0'].geometry}
          material={materials.Material_2}
          position={[1.375, 46.799, -52.874]}
        >
            
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/lab_things.glb')

export default Lab;
