/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ti Kawamoto (https://sketchfab.com/adamselene)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/oculus-rift-cv1-591ff55a0f7b401cbb14fe454175b8b2
Title: Oculus Rift CV1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
// import { expo } from 'maath/dist/declarations/src/easing'

const VR = (props) => {
  const { nodes, materials } = useGLTF('/models/oculus_rift_cv1.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.01, 3.352, -1.11]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_1.geometry}
            material={materials['darkmetal.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_2.geometry}
            material={materials.Headphonemesh}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_3.geometry}
            material={materials.blackfoam}
          />
        </group>
        <group rotation={[0, 0, -Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_1.geometry}
            material={materials.OutsideHMD}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_2.geometry}
            material={materials.ShinierPlastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_3.geometry}
            material={materials.blackspecular}
          />
        </group>
        <group position={[0, -0.083, 0]} rotation={[0, 0, -Math.PI]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_1.geometry}
            material={materials.OutsideHMD}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube017_2.geometry}
            material={materials.blackspecular}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={materials['darkmetal.001']}
          position={[0, 0, 0.448]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025_1.geometry}
          material={materials.material}
          position={[1.121, 6.91, -0.137]}
          rotation={[-0.247, -0.505, -0.163]}
          scale={0.851}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024_1.geometry}
          material={materials['glass.001']}
          position={[0, -0.046, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_1.geometry}
          material={materials.insidemesh}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube023_2.geometry}
          material={materials['Inisiderift.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021_1.geometry}
          material={materials.clothband}
          position={[0, 0.824, 2.478]}
          rotation={[-0.015, 0, 0]}
          scale={[1.108, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020_1.geometry}
          material={materials.bandrubber}
          position={[0, 0.864, 2.498]}
          rotation={[-0.015, 0, 0]}
          scale={[1.108, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019_1.geometry}
          material={materials.clothband}
          position={[0, 0.733, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018_1.geometry}
          material={materials.blackfoam}
          position={[0, -0.093, 0]}
          rotation={[0, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_1.geometry}
          material={materials['darkmetal.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube015_1.geometry}
          material={materials['ShinierPlastic.001']}
          rotation={[0, 0, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_1.geometry}
          material={materials.blackspecular}
          position={[0, 1.452, 2.599]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_1.geometry}
          material={materials.OutsideHMD}
          position={[0, 0.733, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_1.geometry}
          material={materials.ShinierPlasticNoLogo}
          position={[-1.048, -0.199, -1.035]}
          rotation={[Math.PI, 0, 0.158]}
          scale={1.056}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube028_1.geometry}
          material={materials.ShinierPlasticNoLogo}
          position={[-1.295, -0.161, -0.658]}
          rotation={[Math.PI, 0, 0.158]}
          scale={0.476}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube029_1.geometry}
          material={materials.bandrubber}
          position={[0, 0, -0.002]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube027_1.geometry}
          material={materials.blackfoam}
          position={[-1.295, -0.161, -0.62]}
          rotation={[Math.PI, 0, 0.158]}
          scale={0.476}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials['darkmetal.001']}
          position={[0, 3.352, 0.448]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/oculus_rift_cv1.glb')

export default VR